import { getLocale } from '#/paraglide/runtime'

export const dashboardCopy = {
  en: {
    shell: {
      eyebrow: 'Winterest CMS',
      backToSite: 'Back to site',
      nav: {
        overview: 'Overview',
        projects: 'Projects',
        stack: 'Tech Stack',
        media: 'Media',
        social: 'Social Links',
        users: 'Users',
        settings: 'Settings',
        account: 'Account',
      },
      soon: 'Soon',
      logout: 'Log out',
      breadcrumbs: {
        dashboard: 'Dashboard',
        projects: 'Projects',
        stack: 'Tech Stack',
        technologies: 'Technologies',
        categories: 'Categories',
        media: 'Media',
        social: 'Social Links',
        users: 'Users',
        settings: 'Settings',
        account: 'Account',
        new: 'Add New',
        edit: 'Edit',
      },
    },
    overview: {
      title: 'Overview',
      description:
        'A private workspace for keeping Winterest content clear, current, and ready to publish.',
      action: 'Manage projects',
      metrics: {
        total: 'Content items',
        featured: 'Featured work',
        drafts: 'Draft queue',
        published: 'Public-ready',
      },
      chartTitle: 'Content mix',
      chartDescription:
        'A quick read of portfolio content status across projects and media assets.',
      activityTitle: 'Recent focus',
      activityDescription:
        'Use this view to spot what needs polishing or publishing next.',
      quickTitle: 'Quick actions',
      quickDescription:
        'Jump into the places that keep the public portfolio moving.',
      projects: 'Review projects',
      media: 'Organize media',
      states: {
        published: 'Published',
        draft: 'Draft',
        building: 'In progress',
      },
    },
    common: {
      refresh: 'Refresh',
      actions: 'Actions',
      status: 'Status',
      featured: 'Featured',
      visibility: 'Visibility',
      language: 'Language',
      category: 'Category',
      tags: 'Tags',
      entry: 'Entry',
      edit: 'Edit',
      delete: 'Delete',
      back: 'Back',
      loading: 'Loading content...',
      saveError: 'Save failed.',
      deleteError: 'Delete failed.',
      loadError: 'Failed to load content.',
      emptyTitle: 'No entries yet.',
      draftCreated: 'Draft created.',
      changesSaved: 'Changes saved.',
      saving: 'Saving...',
      createDraft: 'Create draft',
      saveChanges: 'Save changes',
      cancel: 'Cancel',
      notice: 'Notice',
    },
    projects: {
      title: 'Projects',
      description:
        'Manage the work shown in the portfolio: project details, highlights, and publishing status.',
      new: 'New project',
      project: 'Project',
      loading: 'Loading projects...',
      emptyTitle: 'No projects yet.',
      emptyDescription:
        'Create the first draft when you are ready to shape a new portfolio entry.',
      loadError: 'Failed to load projects.',
      deleteError: 'Failed to delete project.',
      saveError: 'Project save failed.',
      deleteSaveError: 'Project delete failed.',
      deleteTitle: 'Delete Project',
      deleteConfirm: (title: string) =>
        `Are you sure you want to delete project "${title}"? This action cannot be undone.`,
      newTitle: 'New project',
      newDescription:
        'Create a draft project and refine it before it appears on the public site.',
      editTitle: 'Edit project',
      editDescription:
        'Update the story, links, and publishing state for this portfolio entry.',
      loadingEntry: 'Loading project...',
      notFound: 'Project not found.',
      technologiesTitle: 'Associated Technologies',
      technologiesLoading: 'Loading technologies...',
      noTechnologies: 'No technologies found in Stack Management yet.',
      addTechnologyBtn: 'New Technology',
      addTechnologyEmpty: 'Create your first technology',
      form: {
        mainSettingsTitle: 'Main Project Settings',
        mainSettingsDesc:
          'URL slug, publication status, and visibility configuration.',
        slug: 'Slug',
        slugPlaceholder: 'e.g. cloud-analytics-platform',
        status: 'Status',
        statusPlaceholder: 'Select status',
        statusDraft: 'Draft',
        statusInProgress: 'In Progress',
        statusPublished: 'Published',
        statusArchived: 'Archived',
        visibility: 'Project Visibility',
        visibilityPlaceholder: 'Select visibility',
        visibilityPublic: 'Public',
        visibilityPrivate: 'Private',
        repoVisibility: 'Repository Visibility',
        repoVisibilityPlaceholder: 'Select repository visibility',
        coverImage: 'Cover Image',
        coverImageDesc:
          'Recommended aspect ratio: 16:9 or 21:9 (min. 1200x675px).',
        repoUrl: 'Repository URL',
        repoUrlPlaceholder: 'https://github.com/...',
        demoUrl: 'Demo URL',
        demoUrlPlaceholder: 'https://preview.example.com',
        productionUrl: 'Production URL / Live Site',
        productionUrlPlaceholder: 'https://example.com',
        datesTitle: 'Project Timeline',
        datesDesc: 'Start, completion, and publishing dates for this project.',
        startedAt: 'Start Date',
        startedAtPlaceholder: 'Pick start date',
        completedAt: 'Completion Date',
        completedAtPlaceholder: 'Pick completion date',
        publishedAt: 'Publish Date',
        publishedAtPlaceholder: 'Pick publish date',
        clearDate: 'Clear date',
        featuredTitle: 'Featured Project',
        featuredDesc:
          'Display in the featured projects showcase on the homepage.',
        contentHeading: (lang: string) => `Content (${lang})`,
        contentDesc: (lang: string) =>
          `Title, category, summary, and description in ${lang}.`,
        title: 'Title',
        titlePlaceholder: (lang: string) => `Project title (${lang})`,
        category: 'Category',
        categoryPlaceholder: (lang: string) =>
          `Category (${lang}) e.g. Fullstack Web App`,
        summary: 'Summary',
        summaryPlaceholder: (lang: string) => `Short project summary (${lang})`,
        description: 'Description',
        descriptionPlaceholder: (lang: string) =>
          `Full project description (${lang}). Supports markdown...`,
      },
      table: {
        project: 'Project',
        status: 'Status',
        featured: 'Featured',
        language: 'Language',
        visibility: 'Visibility',
        category: 'Category',
        actions: 'Actions',
        statusDraft: 'Draft',
        statusInProgress: 'In Progress',
        statusPublished: 'Published',
        statusArchived: 'Archived',
        featuredBadge: 'Featured',
        standardBadge: 'Standard',
        visibilityPublic: 'Public',
        visibilityPrivate: 'Private',
      },
    },
    media: {
      title: 'Media Library',
      description:
        'Upload, manage, and organize project cover images and portfolio media assets.',
      emptyTitle: 'No media assets yet.',
      emptyDescription:
        'Upload your first project image or visual asset to get started.',
      uploadTitle: 'Upload New Media',
      uploadDesc:
        'Drag & drop or select image files (PNG, JPG, WebP, GIF, SVG, AVIF) or PDF documents up to 10MB.',
      uploading: 'Uploading image...',
      uploadSuccess: 'Media asset uploaded successfully.',
      uploadError: 'Failed to upload media asset.',
      deleteConfirm:
        'Are you sure you want to delete this media asset? This action cannot be undone.',
      deleteSuccess: 'Media deleted successfully.',
      deleteError: 'Failed to delete media asset.',
      copyUrl: 'Copy URL',
      copied: 'Copied!',
      searchPlaceholder: 'Search media files or alt text...',
      selectFromLibrary: 'Choose from Media Library',
      useSelectedImage: 'Use Selected Image',
      noImagesFound: 'No matching media assets found.',
      totalMedia: 'Total assets',
      preview: 'Preview',
      dropToUpload: 'Drop image here to upload',
      browseFiles: 'Browse files',
      changeImage: 'Change image',
      removeImage: 'Remove image',
      coverImageRecommended:
        'Recommended aspect ratio: 16:9 or 21:9 (min. 1200x675px).',
      directUpload: 'Upload image',
      orPasteUrl: 'Or enter image URL manually',
      tabAll: 'All Assets',
      tabImages: 'Images',
      tabDocuments: 'Documents (PDF)',
      pdfBadge: 'PDF',
      document: 'Document',
      openPdf: 'Preview PDF',
      useSelectedFile: 'Use Selected File',
      noDocumentsFound: 'No PDF documents found.',
      dropToUploadDoc: 'Drop PDF document here to upload',
      uploadDocButton: 'Upload PDF',
    },
    stack: {
      title: 'Tech Stack & Skills',
      description:
        'Manage technologies and skill categories displayed on the portfolio.',
      heading: 'Tech Stack & Skills',
      subheading:
        'Manage technologies and skill categories displayed on the portfolio.',
      newCategory: 'New Category',
      newCategoryDesc: 'Add a new category to group technologies and tools.',
      editCategory: 'Edit Category',
      editCategoryDesc: 'Update technology category details and display order.',
      newTechnology: 'New Technology',
      newTechnologyDesc:
        'Add a technology, framework, or tool to your tech stack.',
      editTechnology: 'Edit Technology',
      editTechnologyDesc:
        'Update technology details, icon, or category associations.',
      tabs: {
        technologies: 'Technologies',
        categories: 'Categories',
      },
      actions: {
        addTechnology: 'Add Technology',
        addCategory: 'Add Category',
        backToStack: 'Back to Tech Stack',
      },
      deleteCategoryConfirm: (name: string) =>
        `Are you sure you want to delete category "${name}"?`,
      deleteCategoryError: 'Failed to delete category.',
      deleteTechConfirm: (name: string) =>
        `Are you sure you want to delete technology "${name}"?`,
      deleteTechError: 'Failed to delete technology.',
      categoriesTable: {
        loading: 'Loading categories...',
        empty: 'No categories yet.',
        addFirst: 'Add First Category',
        columns: {
          order: 'Order',
          name: 'Category Name',
          slug: 'Slug',
          actions: 'Actions',
        },
        tooltips: {
          edit: 'Edit Category',
          delete: 'Delete Category',
        },
      },
      techTable: {
        loading: 'Loading technologies...',
        empty: 'No technologies yet.',
        addFirst: 'Add First Technology',
        columns: {
          icon: 'Icon',
          name: 'Name',
          slug: 'Slug',
          ultimate: 'Ultimate',
          categories: 'Categories',
          actions: 'Actions',
        },
        tooltips: {
          edit: 'Edit Technology',
          delete: 'Delete Technology',
        },
      },
      categoryForm: {
        name: 'Category Name',
        namePlaceholder: 'e.g. Frontend',
        slug: 'Slug URL',
        slugPlaceholder: 'e.g. frontend',
        sortOrder: 'Display Order',
        sortOrderPlaceholder: '1',
        sortOrderDesc:
          'Lower numbers will appear earlier in the category list.',
        save: 'Save Category',
        saving: 'Saving...',
        delete: 'Delete Category',
        deleting: 'Deleting...',
        cancel: 'Cancel',
        saveError: 'Failed to save category.',
        deleteError: 'Failed to delete category.',
        deleteConfirm: (name: string) =>
          `Are you sure you want to delete category "${name}"?`,
      },
      techForm: {
        name: 'Technology Name',
        namePlaceholder: 'e.g. React',
        slug: 'Slug URL',
        slugPlaceholder: 'e.g. react',
        icon: 'Icon URL',
        iconSource: 'Icon Source',
        iconSourceSimple: 'Simple Icons',
        iconSourceCustom: 'Custom URL',
        simpleIconsSlug: 'Simple Icons Identifier',
        simpleIconsSlugPlaceholder: 'e.g. react, typescript, bun',
        simpleIconsDesc:
          'Enter the icon slug from simpleicons.org (e.g. react, bun).',
        customIconUrl: 'Custom Icon URL',
        customIconUrlPlaceholder: 'https://... or /assets/...',
        customIconDesc: 'Enter full image URL (SVG/PNG/WebP).',
        iconPlaceholder: 'https://... or /assets/...',
        iconDesc: 'Enter icon image URL (SVG/PNG/WebP).',
        color: 'Hex Color / CSS',
        colorPlaceholder: '#61DAFB',
        websiteUrl: 'Official Website URL',
        websiteUrlPlaceholder: 'https://react.dev',
        ultimateTitle: 'Ultimate Tech Stack',
        ultimateDesc:
          'Display prominently at the top of the Stack page and Homepage Marquee.',
        categoriesTitle: 'Technology Categories',
        categoriesLoading: 'Loading categories...',
        noCategories: 'No categories yet. Please create a category first.',
        addCategoryBtn: 'New Category',
        addCategoryEmpty: 'Create your first category',
        quickAddTitle: 'Create New Category',
        quickAddDescription:
          'Add a new category quickly without leaving the technology editor.',
        quickAddTechTitle: 'Create New Technology',
        quickAddTechDescription:
          'Add a new technology quickly without leaving the project editor.',
        save: 'Save Technology',
        saving: 'Saving...',
        delete: 'Delete Technology',
        deleting: 'Deleting...',
        cancel: 'Cancel',
        saveError: 'Failed to save technology.',
        deleteError: 'Failed to delete technology.',
        deleteConfirm: (name: string) =>
          `Are you sure you want to delete technology "${name}"?`,
      },
    },
    users: {
      title: 'Users',
      description:
        'Manage users, assign dashboard roles, and configure credentials.',
      new: 'New user',
      newUser: 'Create user',
      editUser: 'Edit user',
      newDescription: 'Add a new user to the dashboard with role permissions.',
      editDescription: 'Update user profile and assign role permissions.',
      resetPasswordTitle: 'Reset password',
      resetPasswordDescription:
        'Set a new password for this user. Active sessions will be signed out.',
      loading: 'Loading users...',
      loadingUser: 'Loading user...',
      notFound: 'User not found.',
      emptyTitle: 'No users found.',
      emptyDescription:
        'Add users to grant dashboard access with granular roles.',
      accessDeniedTitle: 'Owner access only',
      accessDeniedDescription:
        'User management is restricted to accounts with the Owner role.',
      metrics: {
        total: 'Total users',
        owners: 'Owners',
        admins: 'Admins',
        team: 'Editors',
      },
      table: {
        user: 'User',
        email: 'Email',
        role: 'Role',
        sessions: 'Active sessions',
        created: 'Created',
        actions: 'Actions',
      },
      roles: {
        owner: 'Owner',
        admin: 'Admin',
        editor: 'Editor',
        ownerDesc:
          'Full access to users, roles, settings, and all CMS content.',
        adminDesc: 'Manage content, media, and dashboard settings.',
        editorDesc: 'Create and edit portfolio content.',
      },
      form: {
        name: 'Full name',
        namePlaceholder: 'e.g. Your Name',
        email: 'Email address',
        emailPlaceholder: 'e.g. user@example.com',
        role: 'Role',
        password: 'Password',
        passwordPlaceholder: 'Minimum 8 characters',
        newPassword: 'New password',
        saveChanges: 'Save changes',
        createUser: 'Create user',
        resetPasswordButton: 'Update password',
        resettingPassword: 'Updating password...',
        deleteUser: 'Delete user',
        deleteConfirm:
          'Are you sure you want to delete this user? This action cannot be undone.',
        selfDeleteWarning: 'You cannot delete your own account.',
        soleOwnerWarning:
          'You cannot demote or delete the only remaining owner.',
      },
      feedback: {
        created: 'User created successfully.',
        updated: 'User updated successfully.',
        deleted: 'User deleted successfully.',
        passwordReset: 'Password has been reset successfully.',
        saveError: 'Failed to save user.',
        deleteError: 'Failed to delete user.',
        resetError: 'Failed to reset password.',
      },
    },
    social: {
      title: 'Social Links',
      description:
        'Manage public social media links, developer profiles, and direct community channels.',
      addLink: 'Add social link',
      editLink: 'Edit social link',
      dialogTitleNew: 'Add Social Media Link',
      dialogTitleEdit: 'Edit Social Media Link',
      dialogDescription:
        'Configure profile URL, display name, and public visibility for this platform.',
      emptyTitle: 'No social links configured yet',
      emptyDescription:
        'Add your GitHub, LinkedIn, X, or other social profiles to display them across public pages.',
      form: {
        platform: 'Platform',
        platformPlaceholder: 'Select a platform',
        username: 'Username',
        usernamePlaceholder: 'e.g. username or @handle',
        accountName: 'Display name',
        accountNamePlaceholder: 'e.g. Your Name',
        url: 'Profile URL',
        urlPlaceholder: 'https://...',
        isEnabled: 'Visible on public site',
        isEnabledDesc:
          'Toggle whether this link is rendered on the public header, footer, and contact page.',
        sortOrder: 'Display order',
        sortOrderDesc: 'Lower numbers appear first (e.g. 0, 1, 2).',
        save: 'Save link',
        saving: 'Saving...',
        cancel: 'Cancel',
        delete: 'Delete link',
        deleteConfirm: 'Are you sure you want to delete this social link?',
        deleteConfirmDesc:
          'This link will be removed immediately from your public profile.',
      },
      status: {
        active: 'Active',
        inactive: 'Hidden',
      },
      actions: {
        openLink: 'Open URL',
        edit: 'Edit',
        delete: 'Delete',
        toggleEnable: 'Toggle visibility',
      },
      feedback: {
        created: 'Social link added successfully.',
        updated: 'Social link updated successfully.',
        deleted: 'Social link deleted successfully.',
      },
    },
    settings: {
      title: 'Settings',
      description:
        'Manage site identity, contact email, SEO defaults, and system preferences.',
      accessDeniedTitle: 'Owner or Admin access only',
      accessDeniedDescription:
        'System settings are restricted to accounts with Owner or Admin roles.',
      tabs: {
        general: 'General',
        visual: 'Branding & Visual',
        contact: 'Contact',
        seo: 'SEO & Meta',
        system: 'System',
      },
      socialNotice:
        'Social media links are now managed independently in the Social Links menu.',
      goToSocial: 'Manage Social Links',
      form: {
        siteName: 'Site name',
        siteNameDesc: 'Public brand name (default: Winterest).',
        siteTagline: 'Tagline',
        siteTaglineDesc: 'Short headline for branding and hero meta.',
        siteDescription: 'Site summary / bio',
        siteDescriptionDesc: 'Personal intro summary used on public pages.',
        defaultLocale: 'Default language',
        heroVisualUrl: 'Hero Visual / Mascot Image',
        heroVisualDesc:
          'Custom hero image or mascot for the homepage. Leave empty to use the default mascot.',
        cvHeading: 'Curriculum Vitae (CV)',
        cvHeadingDesc:
          'Upload your latest CV in PDF format. Visitors can view and download this file directly from the homepage and resume.',
        cvEnLabel: 'English Version',
        cvEnDesc:
          'Shown to international visitors, and used as the default if the Indonesian version is not added.',
        cvIdLabel: 'Indonesian Version',
        cvIdDesc:
          'Shown when visitors browse in Indonesian. If left empty, your English CV is used automatically.',
        cvFallbackActive:
          'Not uploaded yet. Visitors will see your English CV automatically.',
        cvStatusActive: 'Active',
        cvStatusEmpty: 'Not uploaded',
        cvStatusUsingEn: 'Using English CV',
        selectCvPdf: 'Choose PDF File',
        changeCvPdf: 'Change File',
        removeCvPdf: 'Remove',
        noCvUploaded: 'No PDF file selected yet.',
        publicEmail: 'Public contact email',
        publicEmailDesc:
          'Primary email address displayed for direct inquiries and contact channels.',
        homepageSeoHeading: 'Homepage SEO (Landing Page)',
        homepageSeoDesc:
          'Configure the browser tab title and description specifically for the homepage (/).',
        metaLanguageEn: 'English (EN)',
        metaLanguageId: 'Indonesian (ID)',
        metaTitleEn: 'Homepage Meta Title (English)',
        metaTitleId: 'Homepage Meta Title (Indonesian)',
        metaTitleDesc:
          'Browser tab title and search snippet title specifically for the Homepage.',
        metaDescriptionEn: 'Homepage SEO description (English)',
        metaDescriptionId: 'Homepage SEO description (Indonesian)',
        metaDescriptionDesc: 'Summary shown in search engine snippet results.',
        ogDescriptionEn: 'OpenGraph description (English)',
        ogDescriptionId: 'OpenGraph description (Indonesian)',
        ogDescriptionDesc:
          'Social share description for Twitter/X, LinkedIn, Discord, and WhatsApp.',
        subpageSeoHeading: 'Sub-page Title Template',
        subpageSeoDesc:
          'Configure how titles for all sub-pages (e.g. /about, /projects, /contact, /dashboard) are formatted.',
        metaTitleTemplate: 'Title template for sub-pages',
        metaTitleTemplateDesc:
          'Template for browser tab title where %s represents the page name (e.g. %s | Winterest).',
        templatePreviewLabel: 'Live title preview:',
        templatePreviewExample: 'About | Winterest',
        faviconUrl: 'Favicon / Browser Icon',
        faviconDesc:
          'Small icon displayed in browser tabs and bookmarks (PNG, SVG, or ICO).',
        ogImageUrl: 'OpenGraph Share Image',
        ogImageDesc:
          'Banner image (1200x630px recommended) displayed when sharing website links on social platforms.',
        socialPreviewTitle: 'Social Share Card Preview',
        maintenanceMode: 'Maintenance mode',
        maintenanceModeDesc: 'Show maintenance screen for public visitors.',
        saveChanges: 'Save settings',
        saving: 'Saving settings...',
      },
      feedback: {
        updated: 'Settings saved successfully.',
        saveError: 'Failed to save settings.',
        loadError: 'Failed to load settings.',
      },
    },
    account: {
      title: 'Account Settings',
      description:
        'Manage your personal profile, credentials, and security preferences.',
      profileTitle: 'Profile Information',
      profileDescription:
        'Update your personal details and how you appear in the dashboard.',
      securityTitle: 'Security & Password',
      securityDescription:
        'Ensure your account stays secure by using a strong, unique password.',
      sessionsTitle: 'Active Sessions',
      sessionsDescription:
        'Summary of active browser sessions associated with this account.',
      currentRoleNotice:
        'Your account role is assigned by the platform owner and cannot be edited manually.',
      form: {
        name: 'Full name',
        namePlaceholder: 'e.g. Your Name',
        email: 'Email address',
        emailPlaceholder: 'e.g. user@example.com',
        role: 'Current role',
        currentPassword: 'Current password',
        currentPasswordPlaceholder: 'Enter current password',
        newPassword: 'New password',
        newPasswordPlaceholder: 'Minimum 8 characters',
        confirmPassword: 'Confirm new password',
        confirmPasswordPlaceholder: 'Re-enter new password',
        saveProfile: 'Save profile',
        savingProfile: 'Saving profile...',
        updatePassword: 'Update password',
        updatingPassword: 'Updating password...',
        memberSince: 'Member since',
        activeSessionsCount: 'Active sessions',
      },
      feedback: {
        profileUpdated: 'Profile updated successfully.',
        passwordChanged: 'Password changed successfully.',
        profileError: 'Failed to update profile.',
        passwordError: 'Failed to change password.',
        loadError: 'Failed to load account details.',
      },
      sessions: {
        currentSessionTitle: 'Current Active Browser Session',
        currentSessionDesc:
          'Encrypted and secure active session on this device.',
        activeBadge: 'Active',
        securityTipsTitle: 'Account Security Tips',
        securityTip1:
          'Use a unique password with a mix of uppercase letters, lowercase letters, numbers, and symbols.',
        securityTip2:
          'Never share your login credentials or session tokens with anyone.',
        securityTip3:
          'Always sign out when finished using the dashboard on a shared device.',
      },
    },
    form: {
      title: 'Title',
      slug: 'Slug',
      summary: 'Summary',
      description: 'Description',
      category: 'Category',
      status: 'Status',
      visibility: 'Visibility',
      language: 'Language',
      repositoryUrl: 'Repository URL',
      demoUrl: 'Demo URL',
      caseStudyUrl: 'Detail / Article URL',
      coverImageUrl: 'Cover image URL',
      featured: 'Featured project',
      content: 'Content',
      tags: 'Tags',
    },
  },
  id: {
    shell: {
      eyebrow: 'CMS Winterest',
      backToSite: 'Kembali ke situs',
      nav: {
        overview: 'Ringkasan',
        projects: 'Project',
        stack: 'Tech Stack',
        media: 'Media',
        social: 'Media Sosial',
        users: 'Pengguna',
        settings: 'Pengaturan',
        account: 'Akun',
      },
      soon: 'Nanti',
      logout: 'Keluar',
      breadcrumbs: {
        dashboard: 'Dashboard',
        projects: 'Project',
        stack: 'Tech Stack',
        technologies: 'Teknologi',
        categories: 'Kategori',
        media: 'Media',
        social: 'Media Sosial',
        users: 'Pengguna',
        settings: 'Pengaturan',
        account: 'Akun',
        new: 'Tambah Baru',
        edit: 'Edit',
      },
    },
    overview: {
      title: 'Ringkasan',
      description:
        'Workspace privat untuk menjaga konten Winterest tetap jelas, terbaru, dan siap dipublish.',
      action: 'Kelola project',
      metrics: {
        total: 'Total konten',
        featured: 'Karya pilihan',
        drafts: 'Antrian draft',
        published: 'Siap publik',
      },
      chartTitle: 'Komposisi konten',
      chartDescription:
        'Gambaran cepat status konten portfolio antara project dan aset media.',
      activityTitle: 'Fokus terbaru',
      activityDescription:
        'Gunakan tampilan ini untuk melihat apa yang perlu dipoles atau dipublish berikutnya.',
      quickTitle: 'Aksi cepat',
      quickDescription:
        'Masuk ke area yang menjaga portfolio publik tetap bergerak.',
      projects: 'Review project',
      media: 'Rapikan media',
      states: {
        published: 'Published',
        draft: 'Draft',
        building: 'Dikerjakan',
      },
    },
    common: {
      refresh: 'Refresh',
      actions: 'Aksi',
      status: 'Status',
      featured: 'Pilihan',
      visibility: 'Visibilitas',
      language: 'Bahasa',
      category: 'Kategori',
      tags: 'Tag',
      entry: 'Entry',
      edit: 'Edit',
      delete: 'Hapus',
      back: 'Kembali',
      loading: 'Memuat konten...',
      saveError: 'Gagal menyimpan.',
      deleteError: 'Gagal menghapus.',
      loadError: 'Gagal memuat konten.',
      emptyTitle: 'Belum ada entry.',
      draftCreated: 'Draft dibuat.',
      changesSaved: 'Perubahan disimpan.',
      saving: 'Menyimpan...',
      createDraft: 'Buat draft',
      saveChanges: 'Simpan perubahan',
      cancel: 'Batal',
      notice: 'Pemberitahuan',
    },
    projects: {
      title: 'Project',
      description:
        'Kelola karya yang tampil di portfolio: detail project, highlight, dan status publish.',
      new: 'Project baru',
      project: 'Project',
      loading: 'Memuat project...',
      emptyTitle: 'Belum ada project.',
      emptyDescription:
        'Buat draft pertama saat kamu siap membentuk entry portfolio baru.',
      loadError: 'Gagal memuat project.',
      deleteError: 'Gagal menghapus project.',
      saveError: 'Gagal menyimpan project.',
      deleteSaveError: 'Gagal menghapus project.',
      deleteTitle: 'Hapus Project',
      deleteConfirm: (title: string) =>
        `Apakah Anda yakin ingin menghapus project "${title}"? Tindakan ini tidak dapat dibatalkan.`,
      newTitle: 'Project baru',
      newDescription:
        'Buat draft project dan poles sebelum tampil di situs publik.',
      editTitle: 'Edit project',
      editDescription:
        'Perbarui cerita, link, dan status publish untuk entry portfolio ini.',
      loadingEntry: 'Memuat project...',
      notFound: 'Project tidak ditemukan.',
      technologiesTitle: 'Teknologi Terkait',
      technologiesLoading: 'Memuat teknologi...',
      noTechnologies: 'Belum ada data teknologi di Stack Management.',
      addTechnologyBtn: 'Tambah Teknologi',
      addTechnologyEmpty: 'Tambah teknologi pertama',
      form: {
        mainSettingsTitle: 'Pengaturan Utama Project',
        mainSettingsDesc:
          'Slug URL, status publikasi, dan pengaturan visibilitas.',
        slug: 'Slug',
        slugPlaceholder: 'mis. cloud-analytics-platform',
        status: 'Status',
        statusPlaceholder: 'Pilih status',
        statusDraft: 'Draft',
        statusInProgress: 'Sedang Dikerjakan',
        statusPublished: 'Dipublikasikan',
        statusArchived: 'Diarsipkan',
        visibility: 'Visibilitas Project',
        visibilityPlaceholder: 'Pilih visibilitas',
        visibilityPublic: 'Publik',
        visibilityPrivate: 'Privat',
        repoVisibility: 'Visibilitas Repository',
        repoVisibilityPlaceholder: 'Pilih visibilitas repository',
        coverImage: 'Gambar Cover',
        coverImageDesc:
          'Rasio aspek yang disarankan: 16:9 atau 21:9 (min. 1200x675px).',
        repoUrl: 'URL Repository',
        repoUrlPlaceholder: 'https://github.com/...',
        demoUrl: 'URL Demo',
        demoUrlPlaceholder: 'https://preview.example.com',
        productionUrl: 'URL Production / Live Site',
        productionUrlPlaceholder: 'https://example.com',
        datesTitle: 'Timeline Project',
        datesDesc: 'Tanggal mulai, selesai, dan publish untuk project ini.',
        startedAt: 'Tanggal Mulai',
        startedAtPlaceholder: 'Pilih tanggal mulai',
        completedAt: 'Tanggal Selesai',
        completedAtPlaceholder: 'Pilih tanggal selesai',
        publishedAt: 'Tanggal Publish',
        publishedAtPlaceholder: 'Pilih tanggal publish',
        clearDate: 'Hapus tanggal',
        featuredTitle: 'Project Unggulan',
        featuredDesc:
          'Tampilkan di deretan project unggulan (Featured Projects) pada homepage.',
        contentHeading: (lang: string) => `Konten (${lang})`,
        contentDesc: (lang: string) =>
          `Informasi judul, kategori, ringkasan, dan deskripsi dalam bahasa ${lang}.`,
        title: 'Judul',
        titlePlaceholder: (lang: string) => `Judul project (${lang})`,
        category: 'Kategori',
        categoryPlaceholder: (lang: string) =>
          `Kategori (${lang}) mis. Fullstack Web App`,
        summary: 'Ringkasan',
        summaryPlaceholder: (lang: string) =>
          `Ringkasan singkat project (${lang})`,
        description: 'Deskripsi',
        descriptionPlaceholder: (lang: string) =>
          `Deskripsi lengkap project (${lang}). Mendukung format markdown...`,
      },
      table: {
        project: 'Project',
        status: 'Status',
        featured: 'Unggulan',
        language: 'Bahasa',
        visibility: 'Visibilitas',
        category: 'Kategori',
        actions: 'Aksi',
        statusDraft: 'Draft',
        statusInProgress: 'Sedang Dikerjakan',
        statusPublished: 'Dipublikasikan',
        statusArchived: 'Diarsipkan',
        featuredBadge: 'Unggulan',
        standardBadge: 'Standar',
        visibilityPublic: 'Publik',
        visibilityPrivate: 'Privat',
      },
    },
    media: {
      title: 'Media Library',
      description:
        'Unggah, kelola, dan atur gambar cover project dan aset visual portfolio kamu.',
      emptyTitle: 'Belum ada aset media.',
      emptyDescription:
        'Unggah gambar project atau aset visual pertama kamu untuk memulai.',
      uploadTitle: 'Unggah Media Baru',
      uploadDesc:
        'Tarik & lepas atau pilih file gambar (PNG, JPG, WebP, GIF, SVG, AVIF) atau dokumen PDF hingga 10MB.',
      uploading: 'Mengunggah gambar...',
      uploadSuccess: 'Aset media berhasil diunggah.',
      uploadError: 'Gagal mengunggah aset media.',
      deleteConfirm:
        'Apakah kamu yakin ingin menghapus aset media ini? Tindakan ini tidak dapat dibatalkan.',
      deleteSuccess: 'Media berhasil dihapus.',
      deleteError: 'Gagal menghapus aset media.',
      copyUrl: 'Salin URL',
      copied: 'Disalin!',
      searchPlaceholder: 'Cari nama file atau teks alt...',
      selectFromLibrary: 'Pilih dari Media Library',
      useSelectedImage: 'Gunakan Gambar Terpilih',
      noImagesFound: 'Tidak ada aset media yang cocok.',
      totalMedia: 'Total aset',
      preview: 'Pratinjau',
      dropToUpload: 'Lepaskan gambar di sini untuk mengunggah',
      browseFiles: 'Pilih file',
      changeImage: 'Ganti gambar',
      removeImage: 'Hapus gambar',
      coverImageRecommended:
        'Rasio aspek yang disarankan: 16:9 atau 21:9 (min. 1200x675px).',
      directUpload: 'Unggah gambar',
      orPasteUrl: 'Atau masukkan URL gambar manual',
      tabAll: 'Semua Aset',
      tabImages: 'Gambar',
      tabDocuments: 'Dokumen (PDF)',
      pdfBadge: 'PDF',
      document: 'Dokumen',
      openPdf: 'Pratinjau PDF',
      useSelectedFile: 'Gunakan File Terpilih',
      noDocumentsFound: 'Belum ada dokumen PDF yang diunggah.',
      dropToUploadDoc: 'Lepaskan berkas PDF di sini untuk mengunggah',
      uploadDocButton: 'Unggah PDF',
    },
    stack: {
      title: 'Tech Stack & Keahlian',
      description:
        'Kelola daftar teknologi dan kategori keahlian yang ditampilkan pada portfolio.',
      heading: 'Tech Stack & Keahlian',
      subheading:
        'Kelola daftar teknologi dan kategori keahlian yang ditampilkan pada portfolio.',
      newCategory: 'Kategori Baru',
      newCategoryDesc:
        'Tambahkan kategori baru untuk mengelompokkan teknologi.',
      editCategory: 'Edit Kategori',
      editCategoryDesc:
        'Perbarui informasi kategori teknologi dan urutan tampil.',
      newTechnology: 'Teknologi Baru',
      newTechnologyDesc:
        'Tambahkan teknologi, framework, atau tool ke personal tech stack.',
      editTechnology: 'Edit Teknologi',
      editTechnologyDesc:
        'Perbarui informasi teknologi, icon, atau kategori terkait.',
      tabs: {
        technologies: 'Teknologi',
        categories: 'Kategori',
      },
      actions: {
        addTechnology: 'Tambah Teknologi',
        addCategory: 'Tambah Kategori',
        backToStack: 'Kembali ke Tech Stack',
      },
      deleteCategoryConfirm: (name: string) =>
        `Apakah Anda yakin ingin menghapus kategori "${name}"?`,
      deleteCategoryError: 'Gagal menghapus kategori.',
      deleteTechConfirm: (name: string) =>
        `Apakah Anda yakin ingin menghapus teknologi "${name}"?`,
      deleteTechError: 'Gagal menghapus teknologi.',
      categoriesTable: {
        loading: 'Memuat daftar kategori...',
        empty: 'Belum ada kategori.',
        addFirst: 'Tambah Kategori Pertama',
        columns: {
          order: 'Urutan',
          name: 'Nama Kategori',
          slug: 'Slug',
          actions: 'Aksi',
        },
        tooltips: {
          edit: 'Edit Kategori',
          delete: 'Hapus Kategori',
        },
      },
      techTable: {
        loading: 'Memuat daftar teknologi...',
        empty: 'Belum ada teknologi.',
        addFirst: 'Tambah Teknologi Pertama',
        columns: {
          icon: 'Icon',
          name: 'Nama',
          slug: 'Slug',
          ultimate: 'Ultimate',
          categories: 'Kategori',
          actions: 'Aksi',
        },
        tooltips: {
          edit: 'Edit Teknologi',
          delete: 'Hapus Teknologi',
        },
      },
      categoryForm: {
        name: 'Nama Kategori',
        namePlaceholder: 'mis. Frontend',
        slug: 'Slug URL',
        slugPlaceholder: 'mis. frontend',
        sortOrder: 'Urutan Tampil',
        sortOrderPlaceholder: '1',
        sortOrderDesc:
          'Angka lebih kecil akan ditampilkan lebih awal pada daftar kategori.',
        save: 'Simpan Kategori',
        saving: 'Menyimpan...',
        delete: 'Hapus Kategori',
        deleting: 'Menghapus...',
        cancel: 'Batal',
        saveError: 'Gagal menyimpan kategori.',
        deleteError: 'Gagal menghapus kategori.',
        deleteConfirm: (name: string) =>
          `Apakah Anda yakin ingin menghapus kategori "${name}"?`,
      },
      techForm: {
        name: 'Nama Teknologi',
        namePlaceholder: 'mis. React',
        slug: 'Slug URL',
        slugPlaceholder: 'mis. react',
        icon: 'URL Icon',
        iconSource: 'Sumber Icon',
        iconSourceSimple: 'Simple Icons',
        iconSourceCustom: 'URL Kustom',
        simpleIconsSlug: 'Identifier Simple Icons',
        simpleIconsSlugPlaceholder: 'mis. react, typescript, bun',
        simpleIconsDesc:
          'Masukkan slug icon dari simpleicons.org (mis. react, bun).',
        customIconUrl: 'URL Icon Kustom',
        customIconUrlPlaceholder: 'https://... atau /assets/...',
        customIconDesc: 'Masukkan URL gambar lengkap (SVG/PNG/WebP).',
        iconPlaceholder: 'https://... atau /assets/...',
        iconDesc: 'Masukkan URL gambar icon (SVG/PNG/WebP).',
        color: 'Warna Hex / CSS',
        colorPlaceholder: '#61DAFB',
        websiteUrl: 'Official Website URL',
        websiteUrlPlaceholder: 'https://react.dev',
        ultimateTitle: 'Ultimate Tech Stack',
        ultimateDesc:
          'Tampilkan di bagian paling atas halaman Stack dan Marquee Homepage.',
        categoriesTitle: 'Kategori Teknologi',
        categoriesLoading: 'Memuat kategori...',
        noCategories:
          'Belum ada kategori. Silakan buat kategori baru terlebih dahulu.',
        addCategoryBtn: 'Kategori Baru',
        addCategoryEmpty: 'Buat kategori pertama',
        quickAddTitle: 'Buat Kategori Baru',
        quickAddDescription:
          'Tambah kategori baru dengan cepat tanpa meninggalkan editor teknologi.',
        quickAddTechTitle: 'Tambah Teknologi Baru',
        quickAddTechDescription:
          'Tambah teknologi baru dengan cepat tanpa meninggalkan editor project.',
        save: 'Simpan Teknologi',
        saving: 'Menyimpan...',
        delete: 'Hapus Teknologi',
        deleting: 'Menghapus...',
        cancel: 'Batal',
        saveError: 'Gagal menyimpan teknologi.',
        deleteError: 'Gagal menghapus teknologi.',
        deleteConfirm: (name: string) =>
          `Apakah Anda yakin ingin menghapus teknologi "${name}"?`,
      },
    },
    users: {
      title: 'Pengguna',
      description:
        'Kelola akun pengguna, tentukan role dashboard, dan konfigurasi kredensial.',
      new: 'Pengguna baru',
      newUser: 'Tambah pengguna',
      editUser: 'Edit pengguna',
      newDescription:
        'Tambahkan akun pengguna baru dengan hak akses role tertentu.',
      editDescription: 'Perbarui profil pengguna dan atur hak akses role.',
      resetPasswordTitle: 'Reset password',
      resetPasswordDescription:
        'Tetapkan password baru untuk pengguna ini. Sesi aktif pengguna akan dihentikan.',
      loading: 'Memuat pengguna...',
      loadingUser: 'Memuat data pengguna...',
      notFound: 'Pengguna tidak ditemukan.',
      emptyTitle: 'Belum ada pengguna.',
      emptyDescription:
        'Tambahkan pengguna untuk memberikan akses ke dashboard sesuai role.',
      accessDeniedTitle: 'Akses Khusus Owner',
      accessDeniedDescription:
        'Fitur manajemen pengguna hanya dapat diakses oleh akun dengan role Owner.',
      metrics: {
        total: 'Total pengguna',
        owners: 'Owner',
        admins: 'Admin',
        team: 'Editor',
      },
      table: {
        user: 'Pengguna',
        email: 'Email',
        role: 'Role',
        sessions: 'Sesi aktif',
        created: 'Dibuat',
        actions: 'Aksi',
      },
      roles: {
        owner: 'Owner',
        admin: 'Admin',
        editor: 'Editor',
        ownerDesc:
          'Akses penuh ke manajemen user, role, pengaturan, dan semua konten CMS.',
        adminDesc: 'Kelola konten CMS, media, dan pengaturan dashboard.',
        editorDesc: 'Buat dan edit konten portfolio.',
      },
      form: {
        name: 'Nama lengkap',
        namePlaceholder: 'cth. Nama Anda',
        email: 'Alamat email',
        emailPlaceholder: 'cth. user@example.com',
        role: 'Role',
        password: 'Password',
        passwordPlaceholder: 'Minimal 8 karakter',
        newPassword: 'Password baru',
        saveChanges: 'Simpan perubahan',
        createUser: 'Tambah pengguna',
        resetPasswordButton: 'Perbarui password',
        resettingPassword: 'Memperbarui password...',
        deleteUser: 'Hapus pengguna',
        deleteConfirm:
          'Apakah kamu yakin ingin menghapus pengguna ini? Tindakan ini tidak dapat dibatalkan.',
        selfDeleteWarning: 'Kamu tidak bisa menghapus akunmu sendiri.',
        soleOwnerWarning:
          'Kamu tidak bisa mendegradasi atau menghapus satu-satunya owner yang tersisa.',
      },
      feedback: {
        created: 'Pengguna berhasil ditambahkan.',
        updated: 'Pengguna berhasil diperbarui.',
        deleted: 'Pengguna berhasil dihapus.',
        passwordReset: 'Password berhasil direset.',
        saveError: 'Gagal menyimpan data pengguna.',
        deleteError: 'Gagal menghapus pengguna.',
        resetError: 'Gagal mereset password.',
      },
    },
    social: {
      title: 'Media Sosial',
      description:
        'Kelola tautan media sosial publik, profil pengembang, dan kanal komunitas langsung.',
      addLink: 'Tambah tautan sosial',
      editLink: 'Edit tautan sosial',
      dialogTitleNew: 'Tambah Tautan Media Sosial',
      dialogTitleEdit: 'Edit Tautan Media Sosial',
      dialogDescription:
        'Atur URL profil, nama tampilan, dan visibilitas publik untuk platform ini.',
      emptyTitle: 'Belum ada tautan media sosial',
      emptyDescription:
        'Tambahkan profil GitHub, LinkedIn, X, atau media sosial lainnya untuk ditampilkan di halaman publik.',
      form: {
        platform: 'Platform',
        platformPlaceholder: 'Pilih platform',
        username: 'Username',
        usernamePlaceholder: 'cth. username atau @handle',
        accountName: 'Nama tampilan',
        accountNamePlaceholder: 'cth. Nama Anda',
        url: 'URL Profil',
        urlPlaceholder: 'https://...',
        isEnabled: 'Tampilkan di situs publik',
        isEnabledDesc:
          'Aktifkan untuk menampilkan tautan ini di header, footer, dan halaman kontak publik.',
        sortOrder: 'Urutan tampilan',
        sortOrderDesc: 'Angka lebih kecil tampil lebih awal (cth. 0, 1, 2).',
        save: 'Simpan tautan',
        saving: 'Menyimpan...',
        cancel: 'Batal',
        delete: 'Hapus tautan',
        deleteConfirm: 'Apakah kamu yakin ingin menghapus tautan sosial ini?',
        deleteConfirmDesc:
          'Tautan ini akan segera dihapus dari profil publik kamu.',
      },
      status: {
        active: 'Aktif',
        inactive: 'Disembunyikan',
      },
      actions: {
        openLink: 'Buka URL',
        edit: 'Edit',
        delete: 'Hapus',
        toggleEnable: 'Ubah visibilitas',
      },
      feedback: {
        created: 'Tautan sosial berhasil ditambahkan.',
        updated: 'Tautan sosial berhasil diperbarui.',
        deleted: 'Tautan sosial berhasil dihapus.',
      },
    },
    settings: {
      title: 'Pengaturan',
      description:
        'Kelola identitas situs, email kontak, preferensi SEO, dan pengaturan sistem.',
      accessDeniedTitle: 'Akses Khusus Owner atau Admin',
      accessDeniedDescription:
        'Pengaturan sistem hanya dapat diakses oleh akun dengan role Owner atau Admin.',
      tabs: {
        general: 'Umum',
        visual: 'Branding & Visual',
        contact: 'Kontak',
        seo: 'SEO & Meta',
        system: 'Sistem',
      },
      socialNotice:
        'Tautan media sosial kini dikelola secara mandiri di menu Media Sosial.',
      goToSocial: 'Kelola Media Sosial',
      form: {
        siteName: 'Nama situs',
        siteNameDesc: 'Nama brand publik (bawaan: Winterest).',
        siteTagline: 'Tagline',
        siteTaglineDesc: 'Slogan singkat untuk branding dan meta hero.',
        siteDescription: 'Ringkasan / bio situs',
        siteDescriptionDesc: 'Perkenalan singkat untuk halaman publik.',
        defaultLocale: 'Bahasa bawaan',
        heroVisualUrl: 'Gambar Hero Visual / Maskot',
        heroVisualDesc:
          'Gambar hero atau maskot custom untuk homepage. Kosongkan untuk menggunakan maskot bawaan.',
        cvHeading: 'Curriculum Vitae (CV)',
        cvHeadingDesc:
          'Unggah berkas CV terbaru dalam format PDF. Berkas ini yang akan diunduh pengunjung dari tombol di halaman utama dan resume.',
        cvEnLabel: 'Versi Bahasa Inggris',
        cvEnDesc:
          'Ditampilkan untuk pengunjung internasional, sekaligus jadi pilihan bawaan jika versi Indonesia belum diunggah.',
        cvIdLabel: 'Versi Bahasa Indonesia',
        cvIdDesc:
          'Ditampilkan saat pengunjung membuka situs dalam Bahasa Indonesia. Jika kosong, situs otomatis memakai versi Inggris.',
        cvFallbackActive:
          'Belum diunggah. Pengunjung akan otomatis diarahkan ke versi Inggris.',
        cvStatusActive: 'Aktif',
        cvStatusEmpty: 'Belum ada',
        cvStatusUsingEn: 'Memakai versi Inggris',
        selectCvPdf: 'Pilih Berkas PDF',
        changeCvPdf: 'Ganti Berkas',
        removeCvPdf: 'Hapus',
        noCvUploaded: 'Belum ada berkas PDF yang dipilih.',
        publicEmail: 'Email kontak publik',
        publicEmailDesc:
          'Alamat email utama yang ditampilkan untuk saluran kontak dan pertanyaan langsung.',
        homepageSeoHeading: 'SEO Halaman Beranda',
        homepageSeoDesc:
          'Atur judul tab browser dan deskripsi khusus untuk halaman beranda utama (/).',
        metaLanguageEn: 'Bahasa Inggris (EN)',
        metaLanguageId: 'Bahasa Indonesia (ID)',
        metaTitleEn: 'Judul Meta Beranda (Bahasa Inggris)',
        metaTitleId: 'Judul Meta Beranda (Bahasa Indonesia)',
        metaTitleDesc:
          'Judul tab browser dan snippet pencarian khusus untuk Halaman Beranda.',
        metaDescriptionEn: 'Deskripsi SEO Beranda (Bahasa Inggris)',
        metaDescriptionId: 'Deskripsi SEO Beranda (Bahasa Indonesia)',
        metaDescriptionDesc:
          'Ringkasan yang ditampilkan pada cuplikan hasil mesin pencari untuk beranda.',
        ogDescriptionEn: 'Deskripsi OpenGraph (Bahasa Inggris)',
        ogDescriptionId: 'Deskripsi OpenGraph (Bahasa Indonesia)',
        ogDescriptionDesc:
          'Deskripsi kartu share media sosial (Twitter/X, LinkedIn, Discord, WhatsApp).',
        subpageSeoHeading: 'Template Format Judul Halaman Turunan',
        subpageSeoDesc:
          'Atur format judul browser untuk seluruh halaman turunan (seperti /about, /projects, /contact, /dashboard).',
        metaTitleTemplate: 'Template format judul meta',
        metaTitleTemplateDesc:
          'Format judul tab browser di mana %s akan diganti dengan nama halaman (cth. %s | Winterest).',
        templatePreviewLabel: 'Pratinjau format judul:',
        templatePreviewExample: 'Tentang | Winterest',
        faviconUrl: 'Favicon / Ikon Browser',
        faviconDesc:
          'Ikon kecil yang ditampilkan pada tab browser dan bookmark (PNG, SVG, atau ICO).',
        ogImageUrl: 'Gambar Share OpenGraph',
        ogImageDesc:
          'Gambar banner (disarankan 1200x630px) saat tautan situs dibagikan ke media sosial.',
        socialPreviewTitle: 'Pratinjau Kartu Share Medsos',
        maintenanceMode: 'Mode pemeliharaan',
        maintenanceModeDesc:
          'Tampilkan pesan pemeliharaan untuk pengunjung publik.',
        saveChanges: 'Simpan pengaturan',
        saving: 'Menyimpan pengaturan...',
      },
      feedback: {
        updated: 'Pengaturan berhasil disimpan.',
        saveError: 'Gagal menyimpan pengaturan.',
        loadError: 'Gagal memuat pengaturan.',
      },
    },
    account: {
      title: 'Pengaturan Akun',
      description:
        'Kelola profil pribadi, kata sandi, dan preferensi keamanan akun kamu.',
      profileTitle: 'Informasi Profil',
      profileDescription:
        'Perbarui data pribadi dan informasi akun kamu di dashboard.',
      securityTitle: 'Keamanan & Kata Sandi',
      securityDescription:
        'Jaga keamanan akun kamu dengan menggunakan kata sandi yang kuat.',
      sessionsTitle: 'Sesi Aktif',
      sessionsDescription:
        'Informasi sesi login browser yang terhubung dengan akun ini.',
      currentRoleNotice:
        'Role akun kamu ditetapkan oleh platform owner dan tidak dapat diubah secara mandiri.',
      form: {
        name: 'Nama lengkap',
        namePlaceholder: 'cth. Nama Anda',
        email: 'Alamat email',
        emailPlaceholder: 'cth. user@example.com',
        role: 'Role saat ini',
        currentPassword: 'Kata sandi saat ini',
        currentPasswordPlaceholder: 'Masukkan kata sandi saat ini',
        newPassword: 'Kata sandi baru',
        newPasswordPlaceholder: 'Minimal 8 karakter',
        confirmPassword: 'Konfirmasi kata sandi baru',
        confirmPasswordPlaceholder: 'Masukkan ulang kata sandi baru',
        saveProfile: 'Simpan profil',
        savingProfile: 'Menyimpan profil...',
        updatePassword: 'Perbarui kata sandi',
        updatingPassword: 'Memperbarui kata sandi...',
        memberSince: 'Terdaftar sejak',
        activeSessionsCount: 'Sesi aktif',
      },
      feedback: {
        profileUpdated: 'Profil berhasil diperbarui.',
        passwordChanged: 'Kata sandi berhasil diperbarui.',
        profileError: 'Gagal memperbarui profil.',
        passwordError: 'Gagal memperbarui kata sandi.',
        loadError: 'Gagal memuat data akun.',
      },
      sessions: {
        currentSessionTitle: 'Sesi Browser Saat Ini',
        currentSessionDesc:
          'Sesi tersimpan yang terenkripsi dan aman pada perangkat ini.',
        activeBadge: 'Aktif',
        securityTipsTitle: 'Tips Keamanan Akun',
        securityTip1:
          'Gunakan kata sandi unik dengan kombinasi huruf besar, kecil, angka, dan simbol.',
        securityTip2:
          'Jangan pernah membagikan kredensial login atau token sesi kamu kepada siapapun.',
        securityTip3:
          'Selalu keluar (logout) setelah selesai menggunakan dashboard di perangkat bersama.',
      },
    },
    form: {
      title: 'Judul',
      slug: 'Slug',
      summary: 'Ringkasan',
      description: 'Deskripsi',
      category: 'Kategori',
      status: 'Status',
      visibility: 'Visibilitas',
      language: 'Bahasa',
      repositoryUrl: 'URL repository',
      demoUrl: 'URL demo',
      caseStudyUrl: 'URL Detail / Artikel',
      coverImageUrl: 'URL cover image',
      featured: 'Project pilihan',
      content: 'Konten',
      tags: 'Tag',
    },
  },
} as const

export function getDashboardCopy() {
  return dashboardCopy[getLocale() === 'id' ? 'id' : 'en']
}
