import { getLocale } from '#/paraglide/runtime'

export const dashboardCopy = {
  en: {
    shell: {
      eyebrow: 'Winterest CMS',
      backToSite: 'Back to site',
      systemGroup: 'System',
      pagesGroup: 'Public Pages',
      navPages: {
        home: 'Home',
        projects: 'Projects',
        stack: 'Tech Stack',
        contact: 'Contact',
      },
      nav: {
        overview: 'Overview',
        projects: 'Projects',
        stack: 'Tech Stack',
        media: 'Media',
        social: 'Social Links',
        users: 'Users',
        settings: 'Settings',
        account: 'Account',
      },
      soon: 'Soon',
      logout: 'Log out',
      breadcrumbs: {
        dashboard: 'Dashboard',
        pages: 'Pages',
        home: 'Home',
        projects: 'Projects',
        stack: 'Tech Stack',
        contact: 'Contact',
        technologies: 'Technologies',
        categories: 'Categories',
        media: 'Media',
        social: 'Social Links',
        users: 'Users',
        settings: 'Settings',
        account: 'Account',
        new: 'Add New',
        edit: 'Edit',
      },
    },
    overview: {
      title: 'Overview',
      description:
        'A private workspace for keeping Winterest content clear, current, and ready to publish.',
      action: 'Manage projects',
      metrics: {
        total: 'Content items',
        featured: 'Featured work',
        drafts: 'Draft queue',
        published: 'Public-ready',
      },
      chartTitle: 'Content mix',
      chartDescription:
        'A quick read of portfolio content status across projects and media assets.',
      activityTitle: 'Recent focus',
      activityDescription:
        'Use this view to spot what needs polishing or publishing next.',
      quickTitle: 'Quick actions',
      quickDescription:
        'Jump into the places that keep the public portfolio moving.',
      projects: 'Review projects',
      media: 'Organize media',
      states: {
        published: 'Published',
        draft: 'Draft',
        building: 'Building',
      },
    },
    common: {
      refresh: 'Refresh',
      actions: 'Actions',
      status: 'Status',
      featured: 'Featured',
      visibility: 'Visibility',
      language: 'Language',
      category: 'Category',
      tags: 'Tags',
      entry: 'Entry',
      edit: 'Edit',
      delete: 'Delete',
      back: 'Back',
      loading: 'Loading content...',
      saveError: 'Save failed.',
      deleteError: 'Delete failed.',
      loadError: 'Failed to load content.',
      emptyTitle: 'No entries yet.',
      draftCreated: 'Draft created.',
      changesSaved: 'Changes saved.',
      saving: 'Saving...',
      createDraft: 'Create draft',
      saveChanges: 'Save changes',
      cancel: 'Cancel',
      notice: 'Notice',
      noResults: 'No results found.',
      noResultsFilterDescription:
        'Try adjusting your search or clearing active filters.',
      resetFilter: 'Reset filter',
      resetFilters: 'Reset filters',
      unsavedChangesTitle: 'Unsaved changes',
      unsavedChangesDesc:
        'You have unsaved changes. Are you sure you want to leave? Your changes will be lost.',
      stay: 'Stay',
      leave: 'Leave without saving',
    },
  },
  id: {
    shell: {
      eyebrow: 'CMS Winterest',
      backToSite: 'Kembali ke situs',
      systemGroup: 'Sistem',
      pagesGroup: 'Halaman Publik',
      navPages: {
        home: 'Beranda',
        projects: 'Project',
        stack: 'Tech Stack',
        contact: 'Kontak',
      },
      nav: {
        overview: 'Ringkasan',
        projects: 'Project',
        stack: 'Tech Stack',
        media: 'Media',
        social: 'Media Sosial',
        users: 'Pengguna',
        settings: 'Pengaturan',
        account: 'Akun',
      },
      soon: 'Nanti',
      logout: 'Keluar',
      breadcrumbs: {
        dashboard: 'Dashboard',
        pages: 'Halaman',
        home: 'Beranda',
        projects: 'Project',
        stack: 'Tech Stack',
        contact: 'Kontak',
        technologies: 'Teknologi',
        categories: 'Kategori',
        media: 'Media',
        social: 'Media Sosial',
        users: 'Pengguna',
        settings: 'Pengaturan',
        account: 'Akun',
        new: 'Tambah Baru',
        edit: 'Edit',
      },
    },
    overview: {
      title: 'Ringkasan',
      description:
        'Workspace privat untuk menjaga konten Winterest tetap jelas, terbaru, dan siap dipublish.',
      action: 'Kelola project',
      metrics: {
        total: 'Total konten',
        featured: 'Karya pilihan',
        drafts: 'Antrian draft',
        published: 'Siap publik',
      },
      chartTitle: 'Komposisi konten',
      chartDescription:
        'Gambaran cepat status konten portfolio antara project dan aset media.',
      activityTitle: 'Fokus terbaru',
      activityDescription:
        'Gunakan tampilan ini untuk melihat apa yang perlu dipoles atau dipublish berikutnya.',
      quickTitle: 'Aksi cepat',
      quickDescription:
        'Masuk ke area yang menjaga portfolio publik tetap bergerak.',
      projects: 'Review project',
      media: 'Rapikan media',
      states: {
        published: 'Published',
        draft: 'Draft',
        building: 'Dikerjakan',
      },
    },
    common: {
      refresh: 'Refresh',
      actions: 'Aksi',
      status: 'Status',
      featured: 'Pilihan',
      visibility: 'Visibilitas',
      language: 'Bahasa',
      category: 'Kategori',
      tags: 'Tag',
      entry: 'Entry',
      edit: 'Edit',
      delete: 'Hapus',
      back: 'Kembali',
      loading: 'Memuat konten...',
      saveError: 'Gagal menyimpan.',
      deleteError: 'Gagal menghapus.',
      loadError: 'Gagal memuat konten.',
      emptyTitle: 'Belum ada entry.',
      draftCreated: 'Draft dibuat.',
      changesSaved: 'Perubahan disimpan.',
      saving: 'Menyimpan...',
      createDraft: 'Buat draft',
      saveChanges: 'Simpan perubahan',
      cancel: 'Batal',
      notice: 'Pemberitahuan',
      noResults: 'Tidak ada hasil ditemukan.',
      noResultsFilterDescription:
        'Coba sesuaikan pencarian atau bersihkan filter yang aktif.',
      resetFilter: 'Reset filter',
      resetFilters: 'Reset filter',
      unsavedChangesTitle: 'Perubahan belum disimpan',
      unsavedChangesDesc:
        'Anda memiliki perubahan yang belum disimpan. Apakah Anda yakin ingin meninggalkan halaman ini? Perubahan Anda akan hilang.',
      stay: 'Tetap di sini',
      leave: 'Tinggalkan tanpa menyimpan',
    },
  },
} as const

export function getDashboardCopy() {
  const locale = getLocale() === 'id' ? 'id' : 'en'
  return dashboardCopy[locale]
}
