import { getLocale } from '#/paraglide/runtime'

export const projectsCopy = {
  en: {
    meta: {
      title: 'Projects',
      description:
        'A collection of projects built to solve real problems, academic tasks, and technical explorations by Winterest.',
    },
    list: {
      eyebrow: 'Projects',
      title: 'Projects',
      description:
        'A collection of projects built to solve real problems, academic tasks, and technical explorations.',
      open: 'Open',
      emptyTitle: 'No published projects yet.',
      emptyDescription:
        'I am still preparing the project stories for this page. Check back soon for more detailed work notes.',
      allCategories: 'All',
      searchPlaceholder: 'Search by title, technology, or keywords...',
      noMatchingProjects: 'No projects match your search or filter criteria.',
      noMatchingDescription:
        'Try searching for different keywords or clear your current filter.',
      resetFilters: 'Reset filters',
      projects: 'projects',
      remote: 'git remote',
      sourceTitle: 'Follow the source code and development behind Winterest.',
      repository: 'Repository',
    },
    detail: {
      notFound: 'Project not found',
      notFoundTitle: 'This project does not exist yet.',
      back: 'Back to projects',
      backToProjects: 'Back to projects',
      projects: 'Projects',
      status: 'Status',
      category: 'Category',
      year: 'Year',
      scope: 'Scope',
      problem: 'Problem',
      goal: 'Goal',
      role: 'Role',
      architecture: 'Architecture',
      highlights: 'Highlights',
      decisions: 'Key Decisions',
      nextSteps: 'Next Steps',
      result: 'Result',
      descriptionHeading: 'Project Description',
      noDescription: 'No full description available for this project yet.',
    },
    dashboard: {
      title: 'Projects',
      description:
        'Manage the work shown in the portfolio: project details, highlights, and publishing status.',
      new: 'New project',
      createFirst: 'Create first project',
      project: 'Project',
      projectsLabel: 'projects',
      loading: 'Loading projects...',
      emptyTitle: 'No projects yet.',
      emptyDescription:
        'Create the first draft when you are ready to shape a new portfolio entry.',
      loadError: 'Failed to load projects.',
      deleteError: 'Failed to delete project.',
      searchPlaceholder: 'Search projects by title, category, or summary...',
      noMatchingProjects: 'No matching projects found.',
      saveError: 'Project save failed.',
      deleteSaveError: 'Project delete failed.',
      deleteTitle: 'Delete Project',
      deleteConfirm: (title: string) =>
        `Are you sure you want to delete project "${title}"? This action cannot be undone.`,
      newTitle: 'New project',
      newDescription:
        'Create a draft project and refine it before it appears on the public site.',
      editTitle: 'Edit project',
      editDescription:
        'Update the story, links, and publishing state for this portfolio entry.',
      loadingEntry: 'Loading project...',
      notFound: 'Project not found.',
      technologiesTitle: 'Associated Technologies',
      technologiesLoading: 'Loading technologies...',
      noTechnologies: 'No technologies found in Stack Management yet.',
      addTechnologyBtn: 'New Technology',
      addTechnologyEmpty: 'Create your first technology',
      form: {
        mainSettingsTitle: 'Main Project Settings',
        mainSettingsDesc:
          'URL slug, publication status, and visibility configuration.',
        slug: 'Slug',
        slugPlaceholder: 'e.g. cloud-analytics-platform',
        status: 'Status',
        statusPlaceholder: 'Select status',
        statusDraft: 'Draft',
        statusInProgress: 'In Progress',
        statusPublished: 'Published',
        statusArchived: 'Archived',
        visibility: 'Project Visibility',
        visibilityPlaceholder: 'Select visibility',
        visibilityPublic: 'Public',
        visibilityPrivate: 'Private',
        repoVisibility: 'Repository Visibility',
        repoVisibilityPlaceholder: 'Select repository visibility',
        coverImage: 'Cover Image',
        coverImageDesc:
          'Recommended aspect ratio: 16:9 or 21:9 (min. 1200x675px).',
        repoUrl: 'Repository URL',
        repoUrlPlaceholder: 'https://github.com/...',
        demoUrl: 'Demo URL',
        demoUrlPlaceholder: 'https://preview.example.com',
        productionUrl: 'Production URL / Live Site',
        productionUrlPlaceholder: 'https://example.com',
        datesTitle: 'Project Timeline',
        datesDesc: 'Start, completion, and publishing dates for this project.',
        startedAt: 'Start Date',
        startedAtPlaceholder: 'Pick start date',
        completedAt: 'Completion Date',
        completedAtPlaceholder: 'Pick completion date',
        publishedAt: 'Publish Date',
        publishedAtPlaceholder: 'Pick publish date',
        clearDate: 'Clear date',
        featuredTitle: 'Featured Project',
        featuredDesc:
          'Display in the featured projects showcase on the homepage.',
        contentHeading: (lang: string) => `Content (${lang})`,
        contentDesc: (lang: string) =>
          `Title, category, summary, and description in ${lang}.`,
        title: 'Title',
        titlePlaceholder: (lang: string) => `Project title (${lang})`,
        category: 'Category',
        categoryPlaceholder: (lang: string) =>
          `Category (${lang}) e.g. Fullstack Web App`,
        summary: 'Summary',
        summaryPlaceholder: (lang: string) => `Short project summary (${lang})`,
        description: 'Description',
        descriptionPlaceholder: (lang: string) =>
          `Full project description (${lang}). Supports markdown...`,
        markdownEditor: {
          write: 'Write',
          preview: 'Preview',
          emptyPreview: 'No description content to preview yet.',
          helperText: 'Supports Markdown formatting',
          copyCode: 'Copy code',
          copiedCode: 'Copied!',
        },
      },
      table: {
        allStatus: 'All Status',
        project: 'Project',
        status: 'Status',
        featured: 'Featured',
        language: 'Language',
        visibility: 'Visibility',
        category: 'Category',
        actions: 'Actions',
        statusDraft: 'Draft',
        statusInProgress: 'In Progress',
        statusPublished: 'Published',
        statusArchived: 'Archived',
        featuredBadge: 'Featured',
        standardBadge: 'Standard',
        visibilityPublic: 'Public',
        visibilityPrivate: 'Private',
      },
    },
  },
  id: {
    meta: {
      title: 'Project',
      description:
        'Koleksi proyek yang dibuat berdasarkan masalah nyata, tugas akademik, dan eksplorasi teknis oleh Winterest.',
    },
    list: {
      eyebrow: 'Project',
      title: 'Daftar Project',
      description:
        'Project yang dibuat berdasarkan masalah, tugas, dan eksplorasi teknologi yang pernah kutemui.',
      open: 'Buka',
      emptyTitle: 'Belum ada project yang dipublish.',
      emptyDescription:
        'Aku masih menyiapkan cerita project untuk halaman ini. Nanti akan ada catatan kerja yang lebih lengkap di sini.',
      allCategories: 'Semua',
      searchPlaceholder:
        'Cari berdasarkan judul, teknologi, atau kata kunci...',
      noMatchingProjects:
        'Tidak ada project yang cocok dengan pencarian atau filter.',
      noMatchingDescription:
        'Coba cari dengan kata kunci lain atau bersihkan filter saat ini.',
      resetFilters: 'Reset filter',
      projects: 'project',
      remote: 'git remote',
      sourceTitle: 'Ikuti source code dan perkembangan di balik Winterest.',
      repository: 'Repository',
    },
    detail: {
      notFound: 'Project tidak ditemukan',
      notFoundTitle: 'Project ini belum ada.',
      back: 'Kembali ke project',
      backToProjects: 'Kembali ke project',
      projects: 'Project',
      status: 'Status',
      category: 'Kategori',
      year: 'Tahun',
      scope: 'Scope',
      problem: 'Masalah',
      goal: 'Tujuan',
      role: 'Peran',
      architecture: 'Arsitektur',
      highlights: 'Highlight',
      decisions: 'Keputusan Kunci',
      nextSteps: 'Langkah Berikutnya',
      result: 'Hasil',
      descriptionHeading: 'Deskripsi Project',
      noDescription: 'Belum ada deskripsi lengkap untuk project ini.',
    },
    dashboard: {
      title: 'Project',
      description:
        'Kelola karya yang tampil di portfolio: detail project, highlight, dan status publish.',
      new: 'Project baru',
      createFirst: 'Buat project pertama',
      project: 'Project',
      projectsLabel: 'project',
      loading: 'Memuat project...',
      emptyTitle: 'Belum ada project.',
      emptyDescription:
        'Buat draft pertama saat kamu siap membentuk entry portfolio baru.',
      loadError: 'Gagal memuat project.',
      deleteError: 'Gagal menghapus project.',
      searchPlaceholder:
        'Cari project berdasarkan judul, kategori, atau ringkasan...',
      noMatchingProjects: 'Tidak ada project yang cocok.',
      saveError: 'Gagal menyimpan project.',
      deleteSaveError: 'Gagal menghapus project.',
      deleteTitle: 'Hapus Project',
      deleteConfirm: (title: string) =>
        `Apakah Anda yakin ingin menghapus project "${title}"? Tindakan ini tidak dapat dibatalkan.`,
      newTitle: 'Project baru',
      newDescription:
        'Buat draft project dan poles sebelum tampil di situs publik.',
      editTitle: 'Edit project',
      editDescription:
        'Perbarui cerita, link, dan status publish untuk entry portfolio ini.',
      loadingEntry: 'Memuat project...',
      notFound: 'Project tidak ditemukan.',
      technologiesTitle: 'Teknologi Terkait',
      technologiesLoading: 'Memuat teknologi...',
      noTechnologies: 'Belum ada data teknologi di Stack Management.',
      addTechnologyBtn: 'Tambah Teknologi',
      addTechnologyEmpty: 'Tambah teknologi pertama',
      form: {
        mainSettingsTitle: 'Pengaturan Utama Project',
        mainSettingsDesc:
          'Slug URL, status publikasi, dan pengaturan visibilitas.',
        slug: 'Slug',
        slugPlaceholder: 'mis. cloud-analytics-platform',
        status: 'Status',
        statusPlaceholder: 'Pilih status',
        statusDraft: 'Draft',
        statusInProgress: 'Sedang Dikerjakan',
        statusPublished: 'Dipublikasikan',
        statusArchived: 'Diarsipkan',
        visibility: 'Visibilitas Project',
        visibilityPlaceholder: 'Pilih visibilitas',
        visibilityPublic: 'Publik',
        visibilityPrivate: 'Privat',
        repoVisibility: 'Visibilitas Repository',
        repoVisibilityPlaceholder: 'Pilih visibilitas repository',
        coverImage: 'Gambar Cover',
        coverImageDesc:
          'Rasio aspek yang disarankan: 16:9 atau 21:9 (min. 1200x675px).',
        repoUrl: 'URL Repository',
        repoUrlPlaceholder: 'https://github.com/...',
        demoUrl: 'URL Demo',
        demoUrlPlaceholder: 'https://preview.example.com',
        productionUrl: 'URL Production / Live Site',
        productionUrlPlaceholder: 'https://example.com',
        datesTitle: 'Timeline Project',
        datesDesc: 'Tanggal mulai, selesai, dan publish untuk project ini.',
        startedAt: 'Tanggal Mulai',
        startedAtPlaceholder: 'Pilih tanggal mulai',
        completedAt: 'Tanggal Selesai',
        completedAtPlaceholder: 'Pilih tanggal selesai',
        publishedAt: 'Tanggal Publish',
        publishedAtPlaceholder: 'Pilih tanggal publish',
        clearDate: 'Hapus tanggal',
        featuredTitle: 'Project Unggulan',
        featuredDesc:
          'Tampilkan di deretan project unggulan (Featured Projects) pada homepage.',
        contentHeading: (lang: string) => `Konten (${lang})`,
        contentDesc: (lang: string) =>
          `Informasi judul, kategori, ringkasan, dan deskripsi dalam bahasa ${lang}.`,
        title: 'Judul',
        titlePlaceholder: (lang: string) => `Judul project (${lang})`,
        category: 'Kategori',
        categoryPlaceholder: (lang: string) =>
          `Kategori (${lang}) mis. Fullstack Web App`,
        summary: 'Ringkasan',
        summaryPlaceholder: (lang: string) =>
          `Ringkasan singkat project (${lang})`,
        description: 'Deskripsi',
        descriptionPlaceholder: (lang: string) =>
          `Deskripsi lengkap project (${lang}). Mendukung format markdown...`,
        markdownEditor: {
          write: 'Tulis',
          preview: 'Pratinjau',
          emptyPreview: 'Belum ada konten deskripsi untuk dipratinjau.',
          helperText: 'Mendukung format Markdown',
          copyCode: 'Salin kode',
          copiedCode: 'Tersalin!',
        },
      },
      table: {
        allStatus: 'Semua Status',
        project: 'Project',
        status: 'Status',
        featured: 'Unggulan',
        language: 'Bahasa',
        visibility: 'Visibilitas',
        category: 'Kategori',
        actions: 'Aksi',
        statusDraft: 'Draft',
        statusInProgress: 'Sedang Dikerjakan',
        statusPublished: 'Dipublikasikan',
        statusArchived: 'Diarsipkan',
        featuredBadge: 'Unggulan',
        standardBadge: 'Standar',
        visibilityPublic: 'Publik',
        visibilityPrivate: 'Privat',
      },
    },
  },
} as const

export function getProjectsCopy() {
  const locale = getLocale() === 'id' ? 'id' : 'en'
  return projectsCopy[locale]
}
